# Link the C runtime statically so gdship.exe runs on machines without the Visual C++
# redistributable.
[target.'cfg(all(windows, target_env = "msvc"))']
rustflags = ["-C", "target-feature=+crt-static"]
